services:
    _defaults:
        autowire: true
        autoconfigure: true

    Behatch\HttpCall\Request: ~
    Behat\MinkExtension\Context\MinkAwareContext: ~

    App\Tests\Behat\:
        resource: '../tests/Behat/*'
